apt-get --yes install bc
apt-get --yes install g++
apt-get --yes install gcc
apt-get --yes install grip
apt-get --yes install inotify-tools
apt-get --yes install make
apt-get --yes install net-tools
apt-get --yes install screen
apt-get --yes install socat
apt-get --yes install vim
