apt-get --yes install bc
apt-get --yes install cscope
apt-get --yes install doxygen
apt-get --yes install g++
apt-get --yes install gcc
apt-get --yes install git
apt-get --yes install git-lfs
apt-get --yes install grip
apt-get --yes install inotify-tools
apt-get --yes install libncurses5-dev
apt-get --yes install libncursesw5-dev
apt-get --yes install make
apt-get --yes install net-tools
apt-get --yes install openssh-server
apt-get --yes install screen
apt-get --yes install socat
apt-get --yes install texlive-base
apt-get --yes install texlive-fonts-extra
apt-get --yes install texlive-fonts-recommended
apt-get --yes install texlive-science
apt-get --yes install valgrind
apt-get --yes install vim
